/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 computer.gltf 
Author: dudecon (https://sketchfab.com/dudecon)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/potted-plant-mediterranean-flowering-low-poly-b8950690664342a497154a8ad2787566
Title: Potted Plant, Mediterranean flowering, low poly
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/computer.gltf");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 3, 0, -6]} scale={1}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.Brown} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.Brown} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.White} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.Leaf} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.Petal} />
      </group>
    </group>
  );
}

useGLTF.preload("/computer.gltf");
