name: Build and deploy Next.js app to Azure Web App (Linux)

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        run: npm ci

      - name: Build Next.js (standalone)
        run: npm run build

      # 👉 Package ONLY what Azure needs, with files at the ZIP ROOT
      - name: Package (standalone) on Windows
        shell: pwsh
        run: |
          Remove-Item -Recurse -Force package -ErrorAction SilentlyContinue
          New-Item -ItemType Directory -Path package/.next | Out-Null
          Copy-Item -Recurse .next/standalone package/
          Copy-Item -Recurse .next/static package/.next/static
          if (Test-Path public) { Copy-Item -Recurse public package/public }
          Copy-Item package.json package/
          Compress-Archive -Path package/* -DestinationPath deploy.zip -Force

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: deploy.zip
          path: deploy.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download packaged build
        uses: actions/download-artifact@v4
        with:
          name: deploy.zip

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_B1BC49447EDB4D9FBE3E1DCC54FAC9A8 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_E806FE07B51A41E68FBAB3D88CA8905C }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B2D2474342C94A5BBC143A02EA57AA14 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: azure-linux-porfolio
          slot-name: Production
          package: deploy.zip
